/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hungry.luffy;

import javax.swing.ImageIcon;

/**
 *
 * @author user1
 */
public class TampilanExit extends javax.swing.JFrame {

    /**
     * Creates new form TampilanExit
     */
    public TampilanExit() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yes = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TampilanExitGame/YES.png"))); // NOI18N
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yesMouseExited(evt);
            }
        });
        getContentPane().add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, 40));

        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TampilanExitGame/NO.png"))); // NOI18N
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMouseExited(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TampilanExitGame/tampilanexitfix.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 675, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseEntered
       ImageIcon m = new ImageIcon(getClass().getResource("/TampilanExitGame/YES2.png"));
       yes.setIcon(m);// TODO add your handling code here:
    }//GEN-LAST:event_yesMouseEntered

    private void yesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseExited
           ImageIcon m = new ImageIcon(getClass().getResource("/TampilanExitGame/YES.png"));
       yes.setIcon(m);
    }//GEN-LAST:event_yesMouseExited

    private void noMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseEntered
       ImageIcon m = new ImageIcon(getClass().getResource("/TampilanExitGame/NO2.png"));
       no.setIcon(m);
    }//GEN-LAST:event_noMouseEntered

    private void noMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseExited
       ImageIcon m = new ImageIcon(getClass().getResource("/TampilanExitGame/NO.png"));
       no.setIcon(m);
    }//GEN-LAST:event_noMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanExit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
